# Generated by Django 3.0.8 on 2020-09-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='top_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
