# Generated by Django 3.1.1 on 2020-09-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_meme_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='created',
            new_name='created_on',
        ),
    ]
