# Generated by Django 3.1.1 on 2020-09-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200920_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
