# Generated by Django 3.1.1 on 2020-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200920_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
