# Generated by Django 3.0.8 on 2020-09-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200920_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='color',
            field=models.CharField(choices=[('D', 'black'), ('B', 'blue'), ('R', 'red'), ('G', 'green')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='top_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
