# Generated by Django 3.0.8 on 2020-09-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200921_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='color',
            new_name='text_color',
        ),
    ]
