# Generated by Django 3.0.8 on 2020-09-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200921_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='text_color',
            field=models.CharField(choices=[('black', 'black'), ('blue', 'blue'), ('red', 'red'), ('green', 'green')], default='black', max_length=5),
        ),
    ]
