# Generated by Django 3.0.8 on 2020-09-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200921_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='font',
            field=models.CharField(choices=[('Comic Neue', 'Comic Neue'), ('Just Another Hand', 'Just Another Hand')], default='Comic Neue', max_length=100),
        ),
    ]
