# Generated by Django 3.1.1 on 2020-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font',
            field=models.CharField(choices=[('Comic Neue', 'Comic Neue'), ('Just Another Hand', 'Just Another Hand'), ('Impact, Fantasy', 'Impact, Fantasy')], default='Comic Neue', max_length=100),
        ),
        migrations.AlterField(
            model_name='meme',
            name='photo_URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
