# Generated by Django 3.1.1 on 2020-09-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200923_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font',
            field=models.CharField(choices=[('Comic Neue', 'Comic Neue'), ('Just Another Hand', 'Just Another Hand'), ('Impact, fantasy', 'Impact, fantasy')], default='Comic Neue', max_length=100),
        ),
    ]
