# Generated by Django 3.0.8 on 2020-09-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200923_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='face',
            field=models.CharField(choices=[('Me Gusta', 'https://i.imgur.com/YN5GR31.png'), ('Troll', 'https://i.imgur.com/lS7NuWp.png'), ('Why U new', 'https://i.imgur.com/TyBY8zX.png'), ('Y U NO', 'https://i.imgur.com/zqWWfQu.png'), ('LOL', 'https://i.imgur.com/RNafstk.png'), ('Pepe', 'https://i.imgur.com/dXAPOYu.png'), ('Pepe Smug', 'https://i.imgur.com/0aRNUzu.png'), ('Okay', 'https://i.imgur.com/zIqpk5B.png'), ('No', 'https://i.imgur.com/jMktZhd.png')], default='Me Gusta', max_length=100),
        ),
    ]
