# Generated by Django 3.1.1 on 2020-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_meme_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='face',
            field=models.CharField(blank=True, choices=[('', ''), ('https://i.imgur.com/YN5GR31.png', 'Me Gusta'), ('https://i.imgur.com/lS7NuWp.png', 'Troll'), ('https://i.imgur.com/TyBY8zX.png', 'Why U new'), ('https://i.imgur.com/zqWWfQu.png', 'Y U NO'), ('https://i.imgur.com/RNafstk.png', 'LOL'), ('https://i.imgur.com/dXAPOYu.png', 'Pepe'), ('https://i.imgur.com/0aRNUzu.png', 'Pepe Smug'), ('https://i.imgur.com/zIqpk5B.png', 'Okay'), ('https://i.imgur.com/jMktZhd.png', 'No')], default='', max_length=100),
        ),
    ]
