# Generated by Django 3.0.8 on 2020-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20200923_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='top_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
