# Generated by Django 3.1.1 on 2020-09-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200923_1652'),
        ('main_app', '0017_auto_20200923_1558'),
    ]

    operations = [
    ]
