# Generated by Django 3.0.8 on 2020-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_merge_20200923_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='face',
            field=models.CharField(blank=True, choices=[('', ''), ('https://i.imgur.com/YN5GR31.png', 'Me Gusta'), ('https://i.imgur.com/YOFpfXA.png', 'Troll Face'), ('https://i.imgur.com/TyBY8zX.png', 'Why U new'), ('https://i.imgur.com/zqWWfQu.png', 'Y U NO'), ('https://i.imgur.com/RNafstk.png', 'LOL Face'), ('https://i.imgur.com/dXAPOYu.png', 'Pepe Frog'), ('https://i.imgur.com/0aRNUzu.png', 'Pepe Smug'), ('https://i.imgur.com/Lw1iFG2.png', 'Okay Guy'), ('https://i.imgur.com/FJ1S2YA.png', 'No Guy'), ('https://i.imgur.com/jS8MkcK.png', 'FTS Guy')], default='', max_length=100),
        ),
    ]
