# Generated by Django 3.0.8 on 2020-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20200923_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
