# Generated by Django 3.0.8 on 2020-09-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
