# Generated by Django 3.0.8 on 2020-09-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
