# Generated by Django 3.0.8 on 2020-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_meme_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='users_who_liked',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
