# Generated by Django 3.0.8 on 2020-09-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_meme_users_who_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='users_who_liked',
        ),
    ]
