# Generated by Django 3.0.8 on 2020-09-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20200923_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['id']},
        ),
    ]
