# Generated by Django 3.0.8 on 2020-09-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20200924_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font',
            field=models.CharField(choices=[('Comic Sans MS, Comic Sans, Cursive', 'Comic Sans'), ('Comic Neue', 'Comic New'), ('Just Another Hand', 'Sharpie'), ('Impact, fantasy', 'Impact'), ('Optima, sans-serif', 'Optima'), ('American Typewriter, serif', 'Type-Writer'), ('Luminari, fantasy', 'Folklore'), ('fantasy', 'Folklore Two')], default='Comic Sans MS, Comic Sans, Cursive', max_length=100),
        ),
    ]
