# Generated by Django 3.0.8 on 2020-09-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20200925_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font_size',
            field=models.CharField(blank=True, choices=[('14px', '14pt'), ('16px', '16pt'), ('18px', '18pt'), ('20px', '20pt'), ('22px', '22pt'), ('24px', '24pt'), ('26px', '26pt')], default='20px', max_length=5),
        ),
    ]
