# Generated by Django 3.1.1 on 2020-09-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20200925_0015'),
        ('main_app', '0033_auto_20200924_2251'),
    ]

    operations = [
    ]
