# Generated by Django 3.0.8 on 2020-09-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20200925_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font_background_color',
            field=models.CharField(choices=[('rgba(255, 255, 255, 0)', 'none'), ('black', 'black'), ('white', 'white'), ('blue', 'blue'), ('red', 'red'), ('green', 'green')], default='rgba(255, 255, 255, 0)', max_length=100),
        ),
    ]
