# Generated by Django 3.0.8 on 2020-09-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20200925_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font_background_color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], default='white', max_length=100),
        ),
        migrations.AlterField(
            model_name='meme',
            name='text_color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], default='black', max_length=15),
        ),
    ]
