# Generated by Django 3.1.1 on 2020-09-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20200925_0141'),
        ('main_app', '0035_merge_20200925_0041'),
    ]

    operations = [
    ]
