# Generated by Django 3.0.8 on 2020-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20200930_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font',
            field=models.CharField(choices=[("'villa', sans-serif", 'Meme'), ("'Comic Sans MS', 'Comic Sans', 'Cursive'", 'Comic Sans'), ('Comic Neue', 'Comic New'), ('Just Another Hand', 'Sharpie'), ("'Impact', 'fantasy'", 'Impact'), ("'Optima', 'sans-serif'", 'Optima'), ("'American Typewriter', 'serif'", 'Type-Writer'), ("'Luminari', 'fantasy'", 'Folklore'), ('fantasy', 'Folklore Two')], default="'villa', sans-serif", max_length=100),
        ),
    ]
