# Generated by Django 3.0.8 on 2020-09-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_auto_20200930_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='font_background_color',
            field=models.CharField(choices=[('rgba(0, 0, 0, 0)', 'clear'), ('black', 'black'), ('white', 'white'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], default='rgba(0, 0, 0, 0)', max_length=100),
        ),
    ]
