# Generated by Django 3.1.1 on 2020-10-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20200930_2334'),
        ('main_app', '0038_merge_20200925_0449'),
    ]

    operations = [
    ]
