# Generated by Django 3.1.1 on 2020-10-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20201001_0119'),
        ('main_app', '0041_merge_20201001_0016'),
    ]

    operations = [
    ]
